version: '3'

services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-8.1}-v4-cli
    environment:
      TYPO3_VERSION: ${TYPO3_VERSION:-^11.5}
      typo3DatabaseName: typo3
      typo3DatabaseHost: mysql
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
      STARTUP_COMMAND_1: sudo apt update && sudo apt install --yes graphicsmagick
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app

  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    tmpfs:
      - /var/lib/mysql
