name: CI

on:
  push:
    branches:
     - master
    tags:
      - '*'
  pull_request:
    branches:
     - master
  schedule:
    - cron: '37 1 * * *'

jobs:
  build:
    name: 'PHP ${{ matrix.php }}, TYPO3 ${{ matrix.typo3 }}'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
        typo3:
          - ^11.5
          - ^12.4

    steps:
      - uses: actions/checkout@v4

      - name: Build
        env:
          PHP_VERSION: ${{matrix.php}}
          TYPO3_VERSION: ${{matrix.typo3}}
        run: docker compose run --rm app composer build

      - name: Cleanup
        if: ${{ always() }}
        run: docker compose down --volumes
